# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
locale: en-US
title: "An Aspiring Writer's Haven"
description: "Follow along as I write my heart out and explore the unknown depths of my imagination."
baseurl: "/blog" # the subpath of your site, e.g. "/blog"
url: "https://aspiring-writer.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: https://www.gravatar.com/avatar/8305681be23372ec3c774233546f849f?s=500 # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 350 # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: "/blog/page:num/"

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  books:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      comments: true
  # Recipe defaults
  - scope:
      path: "_books"
      type: books
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Yoela O.
  picture: https://www.gravatar.com/avatar/8305681be23372ec3c774233546f849f?s=300
  # email:
  # twitter:
  links:
    - 
      title: GitHub
      url: https://github.com/Aspiring-Writer
      icon: fas fa-github
    -
      title: GitLab
      url: https://gitlab.com/Aspiring-Writer
      icon: fas fa-gitlab
    - 
      title: Reddit
      url: https://www.reddit.com/user/Y_Mystake_O
      icon: fas fa-reddit
    - 
      title: Goodreads
      url: https://www.goodreads.com/user/show/80834407-bravisha-skietano
      icon: fas fa-goodreads
    -
      title: LibraryThing
      url: https://librarything.com
      icon: fab fa-book
    - 
      title: Spotify
      url: https://open.spotify.com/user/1k11z9bjgv9zmvmecnnfyr4kq?si=a9dbb039e1ee4009
      icon: fas fa-spotify

# Footer Links
footer_links:
  - 
    title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  -
    title: GitHub
    url: https://github.com/Aspiring-Writer/blog
    icon: fas fa-github
