backend:
  name: git-gateway
  branch: 11ty+tailwind 

publish_mode: editorial_workflow
media_folder: "_site/assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    preview_path: "posts/{{category}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "TOC", name: "toc", widget: "boolean", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "select", required: false, options: ["Devotional", "Poetry", "Tutorial", "Study Strategies", "Review"]}
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["devotional", "poetry", "review", "tutorial", "studying", "study strategies", "theology", "holidays", "patience", "angels", "prayer", "weapons", "death", "sorrow", "loss", "depression", "comfort", "OT", "NT"]}
      - label: "Review Stats"
        name: "review"
        widget: "list"
        required: false
        fields:
          - {label: "Movie", name: "movie", widget: "boolean"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Author", name: "author", widget: "string", required: false}
          - {label: "Director", name: "director", widget: "string", required: false}
          - {label: "Producer", name: "producer", widget: "string", required: false}
          - {label: "Actors", name: "actors", widget: "string", required: false}
          - {label: "Release Date", name: "released", widget: "datetime", date_format: "MM DD, YYYY",}
          - {label: "Start Date", name: "start", widget: "datetime"}
          - {label: "End Date", name: "end", widget: "datetime", date_format: "MM DD, YYYY", required: false}
          - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5, step: 0.2}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "characters"
    label: "Characters"
    folder: "src/books/characters"
    create: true
    slug: "{{slug}}"
    preview_path: "books/characters/{{slug}}"
    fields:
      - {label: "Book", name: "category", widget: "select", multiple: true, options: ["Kidnapped and Afraid", "Test My Fire", "Dear Diary", "Past Nightmares. Present Ghosts. Future Peace.", "Court of Shadows and Ruin"]}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Picture", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "select", options: ["Major", "Minor", "Supporting"]}
      - {label: "Role", name: "role", widget: "select", multiple: true, options: ["Protagonist", "Antagonist", "Deuteragonist", "Tertiary", "Confidante", "Love interest", "Foil"]}
      - {label: "Age", name: "age", widget: "number", required: false}
      - {label: "Nationality", name: "nationality", widget: "list", required: false}
      - {label: "Occupation", name: "occupation", widget: "string"}
      - label: "Physical Appearance"
        name: "appearance"
        widget: "list"
        summary: '{{fields.height}}, {{fields.hair}} hair, {{fields.eye}} eyes, {{fields.build}} build, {{fields.features}}'
        fields:
          - {label: "Height", name: "height", widget: "string"}
          - {label: "Hair color", name: "hair", widget: "select", multiple: true, options: ["Black", "Brown", "Blonde", "Red", "Pink", "Blue", "Purple", "Gray", "White", "Ombré"]}
          - {label: "Eye color", name: "eye", widget: "select", options: ["Brown", "Hazel", "Blue", "Green", "Gray", "Amber"]}
          - {label: "Build", name: "build", widget: "select", options: ["Lean and muscular", "Tall and slend", "Short and curvy"]}
          - {label: "Distinguishing features", name: "features", widget: "text", hint: "Tattoos, scars, birthmarks, etc.", required: false}
          - {label: "Accessories", name: "accessories", widget: "string", hint: "Glasses, jewelry, etc.", required: false}
          - {label: "Grooming", name: "grooming", widget: "select", options: ["Disheveled", "Untidy but clean", "Smart, very put together"], required: false}
          - {label: "Health", name: "health", widget: "string", default: "Fully healthy; no issues", required: false}
      - {label: "Psychology", name: "psych", widget: "select", multiple: true, options: ["Optimist", "Pragmatist", "Pessimist", "Skeptic", "Cynic", "Introvert", "Extrovert", "Street-smart", "Book-smart"]}
      - label: "Relationships"
        name: "relationships"
        widget: "list"
        required: false
        fields:
          - {label: "Father", name: "father", widget: "relation", collection: "characters", search_fields: ["title", "occupation"], value_field: "title"}
          - {label: "Mother", name: "mother", widget: "relation", collection: "characters", search_fields: ["title", "occupation"], value_field: "title"}
          - {label: "Siblings", name: "siblings", widget: "relation", collection: "characters", search_fields: ["title", "occupation"], value_field: "title", multiple: true}
          - {label: "Friends", name: "friends", widget: "relation", collection: "characters", search_fields: ["title", "occupation"], value_field: "title", multiple: true}
          - {label: "Love Interest", name: "love", widget: "relation", collection: "characters", search_fields: ["title", "occupation"], value_field: "title"}
      - {label: "Biggest flaw", name: "flaw", widget: "string", required: false}
      - {label: "Biggest strength", name: "strength", widget: "string", required: false}
      - {label: "Biggest fear", name: "fear", widget: "string", required: false}
      - {label: "Goal", name: "goal", widget: "string", required: false}
      - {label: "Motivation", name: "motivation", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "kidnapped-and-afraid"
    label: "KaA Chapters"
    folder: "src/books/kidnapped-and-afraid"
    create: true
    slug: "{{order}}"
    preview_path: "books/kidnapped-and-afraid/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "Kidnapped and Afraid"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Order", name: "order", widget: "number", min: 0}
      - {label: "Prev", name: "prev", widget: "string", required: false}
      - {label: "Next", name: "next", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "test-my-fire"
    label: "TMF Chapters"
    folder: "src/books/test-my-fire"
    create: true
    slug: "{{order}}"
    preview_path: "books/test-my-fire/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "Test My Fire"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Order", name: "order", widget: "number", min: 0}
      - {label: "Prev", name: "prev", widget: "string", required: false}
      - {label: "Next", name: "next", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "dear-diary"
    label: "DD Chapters"
    folder: "src/books/dear-diary"
    create: true
    slug: "{{order}}"
    preview_path: "books/dear-diary/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "Dear Diary"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Order", name: "order", widget: "number", min: 0}
      - {label: "Prev", name: "prev", widget: "string", required: false}
      - {label: "Next", name: "next", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "past-nightmares-present-ghosts-future-fears"
    label: "PNPGFF Chapters"
    folder: "src/books/past-nightmares-present-ghosts-future-peace"
    create: true
    slug: "{{order}}"
    preview_path: "books/past-nightmares-present-ghosts-future-peace/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "Past Nightmares. Present Ghosts. Future Peace"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Order", name: "order", widget: "number", min: 0}
      - {label: "Prev", name: "prev", widget: "string", required: false}
      - {label: "Next", name: "next", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "court-of-shadows-and-ruin"
    label: "CoSaR Chapters"
    folder: "src/books/court-of-shadows-and-ruin"
    create: true
    slug: "{{order}}"
    preview_path: "books/court-of-shadows-and-ruin/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "Court of Shadows and Ruin"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Order", name: "order", widget: "number", min: 0}
      - {label: "Prev", name: "prev", widget: "string", required: false}
      - {label: "Next", name: "next", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
